package com.bekircaglar.flaggie

 class Flagmap{
  val flagmap: HashMap<String,Int> = HashMap()

  init {

   flagmap["United Arab Emirates"] = R.drawable.ae
   flagmap["Afghanistan"] = R.drawable.af
   flagmap["Antigua and Barbuda"] = R.drawable.ag
   flagmap["Anguilla"] = R.drawable.ai
   flagmap["Albania"] = R.drawable.al
   flagmap["Armenia"] = R.drawable.am
   flagmap["Angola"] = R.drawable.ao
   flagmap["Antarctica"] = R.drawable.aq
   flagmap["Argentina"] = R.drawable.ar
   flagmap["Austria"] = R.drawable.at
   flagmap["Australia"] = R.drawable.au
   flagmap["Aruba"] = R.drawable.aw
   flagmap["Åland Islands"] = R.drawable.ax
   flagmap["Azerbaijan"] = R.drawable.az
   flagmap["Bosnia and Herzegovina"] = R.drawable.ba
   flagmap["Barbados"] = R.drawable.bb
   flagmap["Bangladesh"] = R.drawable.bd
   flagmap["Belgium"] = R.drawable.be
   flagmap["Burkina Faso"] = R.drawable.bf
   flagmap["Bulgaria"] = R.drawable.bg
   flagmap["Bahrain"] = R.drawable.bh
   flagmap["Burundi"] = R.drawable.bi
   flagmap["Benin"] = R.drawable.bj
   flagmap["Saint Barthélemy"] = R.drawable.bl
   flagmap["Bermuda"] = R.drawable.bm
   flagmap["Brunei"] = R.drawable.bn
   flagmap["Bolivia"] = R.drawable.bo
   flagmap["Caribbean Netherlands"] = R.drawable.bq
   flagmap["Brazil"] = R.drawable.br
   flagmap["Bahamas"] = R.drawable.bs
   flagmap["Bhutan"] = R.drawable.bt
   flagmap["Bouvet Island"] = R.drawable.bv
   flagmap["Botswana"] = R.drawable.bw
   flagmap["Belarus"] = R.drawable.by
   flagmap["Belize"] = R.drawable.bz
   flagmap["Canada"] = R.drawable.ca
   flagmap["Cocos (Keeling) Islands"] = R.drawable.cc
   flagmap["DR Congo"] = R.drawable.cd
   flagmap["Central African Republic"] = R.drawable.cf
   flagmap["Republic of the Congo"] = R.drawable.cg
   flagmap["Switzerland"] = R.drawable.ch
   flagmap["Côte d'Ivoire (Ivory Coast)"] = R.drawable.ci
   flagmap["Cook Islands"] = R.drawable.ck
   flagmap["Chile"] = R.drawable.cl
   flagmap["Cameroon"] = R.drawable.cm
   flagmap["China"] = R.drawable.cn
   flagmap["Colombia"] = R.drawable.co
   flagmap["Costa Rica"] = R.drawable.cr
   flagmap["Cuba"] = R.drawable.cu
   flagmap["Cape Verde"] = R.drawable.cv
   flagmap["Curaçao"] = R.drawable.cw
   flagmap["Christmas Island"] = R.drawable.cx
   flagmap["Cyprus"] = R.drawable.cy
   flagmap["Czechia"] = R.drawable.cz
   flagmap["Germany"] = R.drawable.de
   flagmap["Djibouti"] = R.drawable.dj
   flagmap["Denmark"] = R.drawable.dk
   flagmap["Dominica"] = R.drawable.dm
   flagmap["Algeria"] = R.drawable.dz
   flagmap["Ecuador"] = R.drawable.ec
   flagmap["Estonia"] = R.drawable.ee
   flagmap["Egypt"] = R.drawable.eg
   flagmap["Western Sahara"] = R.drawable.eh
   flagmap["Eritrea"] = R.drawable.er
   flagmap["Spain"] = R.drawable.es
   flagmap["Ethiopia"] = R.drawable.et
   flagmap["Finland"] = R.drawable.fi
   flagmap["Fiji"] = R.drawable.fj
   flagmap["Falkland Islands"] = R.drawable.fk
   flagmap["Micronesia"] = R.drawable.fm
   flagmap["Faroe Islands"] = R.drawable.fo
   flagmap["France"] = R.drawable.fr
   flagmap["Gabon"] = R.drawable.ga
   flagmap["United Kingdom"] = R.drawable.gb
   flagmap["Grenada"] = R.drawable.gd
   flagmap["Georgia"] = R.drawable.ge
   flagmap["French Guiana"] = R.drawable.gf
   flagmap["Guernsey"] = R.drawable.gg
   flagmap["Ghana"] = R.drawable.gh
   flagmap["Gibraltar"] = R.drawable.gi
   flagmap["Greenland"] = R.drawable.gl
   flagmap["Gambia"] = R.drawable.gm
   flagmap["Guinea"] = R.drawable.gn
   flagmap["Guadeloupe"] = R.drawable.gp
   flagmap["Equatorial Guinea"] = R.drawable.gq
   flagmap["Greece"] = R.drawable.gr
   flagmap["South Georgia"] = R.drawable.gs
   flagmap["Guatemala"] = R.drawable.gt
   flagmap["Guam"] = R.drawable.gu
   flagmap["Guinea-Bissau"] = R.drawable.gw
   flagmap["Guyana"] = R.drawable.gy
   flagmap["Hong Kong"] = R.drawable.hk
   flagmap["Heard Island and McDonald Islands"] = R.drawable.hm
   flagmap["Honduras"] = R.drawable.hn
   flagmap["Croatia"] = R.drawable.hr
   flagmap["Haiti"] = R.drawable.ht
   flagmap["Hungary"] = R.drawable.hu
   flagmap["Indonesia"] = R.drawable.id
   flagmap["Ireland"] = R.drawable.ie
   flagmap["Israel"] = R.drawable.il
   flagmap["Isle of Man"] = R.drawable.im
   flagmap["British Indian Ocean Territory"] = R.drawable.io
   flagmap["Iraq"] = R.drawable.iq
   flagmap["Iran"] = R.drawable.ir
   flagmap["Italy"] = R.drawable.it
   flagmap["Jersey"] = R.drawable.je
   flagmap["Jamaica"] = R.drawable.jm
   flagmap["Jordan"] = R.drawable.jo
   flagmap["Japan"] = R.drawable.jp
   flagmap["Kenya"] = R.drawable.ke
   flagmap["Kyrgyzstan"] = R.drawable.kg
   flagmap["Cambodia"] = R.drawable.kh
   flagmap["Kiribati"] = R.drawable.ki
   flagmap["Comoros"] = R.drawable.km
   flagmap["Saint Kitts and Nevis"] = R.drawable.kn
   flagmap["North Korea"] = R.drawable.kp
   flagmap["South Korea"] = R.drawable.kr
   flagmap["Kuwait"] = R.drawable.kw
   flagmap["Cayman Islands"] = R.drawable.ky
   flagmap["Kazakhstan"] = R.drawable.kz
   flagmap["Laos"] = R.drawable.la
   flagmap["Lebanon"] = R.drawable.lb
   flagmap["Saint Lucia"] = R.drawable.lc
   flagmap["Liechtenstein"] = R.drawable.li
   flagmap["Sri Lanka"] = R.drawable.lk
   flagmap["Liberia"] = R.drawable.lr
   flagmap["Lesotho"] = R.drawable.ls
   flagmap["Lithuania"] = R.drawable.lt
   flagmap["Luxembourg"] = R.drawable.lu
   flagmap["Latvia"] = R.drawable.lv
   flagmap["Libya"] = R.drawable.ly
   flagmap["Morocco"] = R.drawable.ma
   flagmap["Monaco"] = R.drawable.mc
   flagmap["Moldova"] = R.drawable.md
   flagmap["Montenegro"] = R.drawable.me
   flagmap["Saint Martin"] = R.drawable.mf
   flagmap["Madagascar"] = R.drawable.mg
   flagmap["Marshall Islands"] = R.drawable.mh
   flagmap["North Macedonia"] = R.drawable.mk
   flagmap["Mali"] = R.drawable.ml
   flagmap["Myanmar"] = R.drawable.mm
   flagmap["Mongolia"] = R.drawable.mn
   flagmap["Macao"] = R.drawable.mo
   flagmap["Northern Mariana Islands"] = R.drawable.mp
   flagmap["Martinique"] = R.drawable.mq
   flagmap["Mauritania"] = R.drawable.mr
   flagmap["Montserrat"] = R.drawable.ms
   flagmap["Malta"] = R.drawable.mt
   flagmap["Mauritius"] = R.drawable.mu
   flagmap["Maldives"] = R.drawable.mv
   flagmap["Malawi"] = R.drawable.mw
   flagmap["Mexico"] = R.drawable.mx
   flagmap["Malaysia"] = R.drawable.my
   flagmap["Mozambique"] = R.drawable.mz
   flagmap["Namibia"] = R.drawable.na
   flagmap["New Caledonia"] = R.drawable.nc
   flagmap["Niger"] = R.drawable.ne
   flagmap["Norfolk Island"] = R.drawable.nf
   flagmap["Nigeria"] = R.drawable.ng
   flagmap["Nicaragua"] = R.drawable.ni
   flagmap["Netherlands"] = R.drawable.nl
   flagmap["Norway"] = R.drawable.no
   flagmap["Nepal"] = R.drawable.np
   flagmap["Nauru"] = R.drawable.nr
   flagmap["Niue"] = R.drawable.nu
   flagmap["New Zealand"] = R.drawable.nz
   flagmap["Oman"] = R.drawable.om
   flagmap["Panama"] = R.drawable.pa
   flagmap["Peru"] = R.drawable.pe
   flagmap["French Polynesia"] = R.drawable.pf
   flagmap["Papua New Guinea"] = R.drawable.pg
   flagmap["Philippines"] = R.drawable.ph
   flagmap["Pakistan"] = R.drawable.pk
   flagmap["Poland"] = R.drawable.pl
   flagmap["Saint Pierre and Miquelon"] = R.drawable.pm
   flagmap["Pitcairn Islands"] = R.drawable.pn
   flagmap["Puerto Rico"] = R.drawable.pr
   flagmap["Palestine"] = R.drawable.ps
   flagmap["Portugal"] = R.drawable.pt
   flagmap["Palau"] = R.drawable.pw
   flagmap["Paraguay"] = R.drawable.py
   flagmap["Qatar"] = R.drawable.qa
   flagmap["Réunion"] = R.drawable.re
   flagmap["Romania"] = R.drawable.ro
   flagmap["Serbia"] = R.drawable.rs
   flagmap["Russia"] = R.drawable.ru
   flagmap["Rwanda"] = R.drawable.rw
   flagmap["Saudi Arabia"] = R.drawable.sa
   flagmap["Solomon Islands"] = R.drawable.sb
   flagmap["Seychelles"] = R.drawable.sc
   flagmap["Sudan"] = R.drawable.sd
   flagmap["Sweden"] = R.drawable.se
   flagmap["Singapore"] = R.drawable.sg
   flagmap["Saint Helena"] = R.drawable.sh
   flagmap["Slovenia"] = R.drawable.si
   flagmap["Svalbard and Jan Mayen"] = R.drawable.sj
   flagmap["Slovakia"] = R.drawable.sk
   flagmap["Sierra Leone"] = R.drawable.sl
   flagmap["San Marino"] = R.drawable.sm
   flagmap["Senegal"] = R.drawable.sn
   flagmap["Somalia"] = R.drawable.so
   flagmap["Suriname"] = R.drawable.sr
   flagmap["South Sudan"] = R.drawable.ss
   flagmap["São Tomé and Príncipe"] = R.drawable.st
   flagmap["El Salvador"] = R.drawable.sv
   flagmap["Sint Maarten"] = R.drawable.sx
   flagmap["Syria"] = R.drawable.sy
   flagmap["Eswatini (Swaziland)"] = R.drawable.sz
   flagmap["Turks and Caicos Islands"] = R.drawable.tc
   flagmap["Chad"] = R.drawable.td
   flagmap["French Southern and Antarctic Lands"] = R.drawable.tf
   flagmap["Togo"] = R.drawable.tg
   flagmap["Thailand"] = R.drawable.th
   flagmap["Tajikistan"] = R.drawable.tj
   flagmap["Tokelau"] = R.drawable.tk
   flagmap["Timor-Leste"] = R.drawable.tl
   flagmap["Turkmenistan"] = R.drawable.tm
   flagmap["Tunisia"] = R.drawable.tn
   flagmap["Tonga"] = R.drawable.to
   flagmap["Turkey"] = R.drawable.tr
   flagmap["Trinidad and Tobago"] = R.drawable.tt
   flagmap["Tuvalu"] = R.drawable.tv
   flagmap["Taiwan"] = R.drawable.tw
   flagmap["Tanzania"] = R.drawable.tz
   flagmap["Ukraine"] = R.drawable.ua
   flagmap["Uganda"] = R.drawable.ug
   flagmap["United States"] = R.drawable.us
   flagmap["Uruguay"] = R.drawable.uy
   flagmap["Uzbekistan"] = R.drawable.uz
   flagmap["Vatican City"] = R.drawable.va
   flagmap["Saint Vincent and the Grenadines"] = R.drawable.vc
   flagmap["Venezuela"] = R.drawable.ve
   flagmap["British Virgin Islands"] = R.drawable.vg
   flagmap["U.S. Virgin Islands"] = R.drawable.vi
   flagmap["Vietnam"] = R.drawable.vn
   flagmap["Vanuatu"] = R.drawable.vu
   flagmap["Wallis and Futuna"] = R.drawable.wf
   flagmap["Samoa"] = R.drawable.ws
   flagmap["Kosovo"] = R.drawable.xk
   flagmap["Yemen"] = R.drawable.ye
   flagmap["Mayotte"] = R.drawable.yt
   flagmap["South Africa"] = R.drawable.za
   flagmap["Zambia"] = R.drawable.zm
   flagmap["Zimbabwe"] = R.drawable.zw
  }

}